# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.SmallIntegerField(verbose_name='批次')),
                ('goal', models.TextField(verbose_name='阶段计划')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('sender', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=64)),
                ('amount_goal', models.PositiveIntegerField(default=10000, verbose_name='金额')),
                ('time_limit', models.DateField(auto_now_add=True)),
                ('brief', models.TextField(verbose_name='项目简介')),
                ('file_adr', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '未审核'), (1, '审核中'), (2, '审核通过'), (3, '审核未通过')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(db_index=True, max_length=32)),
                ('times', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=64)),
                ('role', models.ManyToManyField(to='jiuchai.Role')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('id_code', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiuchai.UserInfo'),
        ),
        migrations.AddField(
            model_name='batch',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiuchai.Projects'),
        ),
    ]
