# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiuchai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='award',
            field=models.CharField(max_length=128, null=True, verbose_name='回报'),
        ),
    ]
