# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiuchai', '0003_auto_20180803_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
