# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiuchai', '0004_auto_20180803_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='goal',
            field=models.TextField(null=True, verbose_name='项目计划'),
        ),
    ]
