# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiuchai', '0005_projects_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='goal',
            field=models.TextField(verbose_name='项目计划'),
        ),
    ]
